# Generated by Django 6.0.3 on 2026-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioholding',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
